apiVersion: v1
kind: Pod
metadata:
  name: public-pod
  labels:
    app: public-app
spec:
  containers:
    - name: webserver-pod
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
