apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rcontroller

spec:
  template:
    metadata:
      name: server
      labels:
        app: kloudkode-app
    spec:
      containers:
        - name: server-container
          image: httpd
  replicas: 5
  selector:
    app: kloudkode-app
