org: "<your_org_name>>"
service: cost-explorer

provider:
  name: aws
  runtime: python3.12

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true

functions:
  hello:
    handler: handler.lambda_handler
    layers:
      - !Ref PythonRequirementsLambdaLayer
    events:
      - eventBridge:
          enabled: true
          description: trigger cost explorer lambda at 2 A.M. everyday
          schedule: cron(00 02 * * ? *)