org: "serverless-org-name"
service: cost-explorer

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.lambda_handler
    events:
      - eventBridge:
          enabled: true
          description: trigger cost explorer lambda at 2 A.M. everyday
          schedule: cron(00 02 * * ? *)
